//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JPSoftworks.ChangeCaseExtension.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JPSoftworks.ChangeCaseExtension.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No text in clipboard.
        /// </summary>
        internal static string Command_ClipboardPreview_EmptyClipboard {
            get {
                return ResourceManager.GetString("Command_ClipboardPreview_EmptyClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard Preview.
        /// </summary>
        internal static string Command_ClipboardPreview_Title {
            get {
                return ResourceManager.GetString("Command_ClipboardPreview_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy and keep open.
        /// </summary>
        internal static string Command_CopyAndKeepOpen_Title {
            get {
                return ResourceManager.GetString("Command_CopyAndKeepOpen_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string Command_Paste_Title {
            get {
                return ResourceManager.GetString("Command_Paste_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pinned to the top.
        /// </summary>
        internal static string Command_Pin_Result {
            get {
                return ResourceManager.GetString("Command_Pin_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin.
        /// </summary>
        internal static string Command_Pin_Title {
            get {
                return ResourceManager.GetString("Command_Pin_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pinned.
        /// </summary>
        internal static string Command_PinnedTransformation_Pinned {
            get {
                return ResourceManager.GetString("Command_PinnedTransformation_Pinned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to recently used.
        /// </summary>
        internal static string Command_RecentTranformations_RecentlyUsed {
            get {
                return ResourceManager.GetString("Command_RecentTranformations_RecentlyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split to words and use following text instead.
        /// </summary>
        internal static string Command_SplitSpecial_Detail_Title {
            get {
                return ResourceManager.GetString("Command_SplitSpecial_Detail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-space word separator detected; decode the string into separate words.
        /// </summary>
        internal static string Command_SplitSpecial_Subtitle {
            get {
                return ResourceManager.GetString("Command_SplitSpecial_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split input using special characters.
        /// </summary>
        internal static string Command_SplitSpecial_Title {
            get {
                return ResourceManager.GetString("Command_SplitSpecial_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpinned.
        /// </summary>
        internal static string Command_Unpin_Result {
            get {
                return ResourceManager.GetString("Command_Unpin_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpin.
        /// </summary>
        internal static string Command_Unpin_Title {
            get {
                return ResourceManager.GetString("Command_Unpin_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied to clipboard.
        /// </summary>
        internal static string CommandResult_CopiedToClipboard {
            get {
                return ResourceManager.GetString("CommandResult_CopiedToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pasting to active window....
        /// </summary>
        internal static string CommandResult_Pasting {
            get {
                return ResourceManager.GetString("CommandResult_Pasting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type text to input above or copy text to your Clipboard to view results.
        /// </summary>
        internal static string Page_ChangeCase_EmptyContent_Subtitle {
            get {
                return ResourceManager.GetString("Page_ChangeCase_EmptyContent_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to show.
        /// </summary>
        internal static string Page_ChangeCase_EmptyContent_Title {
            get {
                return ResourceManager.GetString("Page_ChangeCase_EmptyContent_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string Page_ChangeCase_Name {
            get {
                return ResourceManager.GetString("Page_ChangeCase_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type text to transform, or leave empty to transform text in the Clipboard....
        /// </summary>
        internal static string Page_ChangeCase_Placeholder {
            get {
                return ResourceManager.GetString("Page_ChangeCase_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the case of text.
        /// </summary>
        internal static string Page_ChangeCase_Subtitle {
            get {
                return ResourceManager.GetString("Page_ChangeCase_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Case.
        /// </summary>
        internal static string Page_ChangeCase_Title {
            get {
                return ResourceManager.GetString("Page_ChangeCase_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string Settings_RecentItemsCount_Choice_1 {
            get {
                return ResourceManager.GetString("Settings_RecentItemsCount_Choice_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string Settings_RecentItemsCount_Choice_2 {
            get {
                return ResourceManager.GetString("Settings_RecentItemsCount_Choice_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string Settings_RecentItemsCount_Choice_3 {
            get {
                return ResourceManager.GetString("Settings_RecentItemsCount_Choice_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string Settings_RecentItemsCount_Choice_None {
            get {
                return ResourceManager.GetString("Settings_RecentItemsCount_Choice_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of displayed recently used transformations.
        /// </summary>
        internal static string Settings_RecentItemsCount_Label {
            get {
                return ResourceManager.GetString("Settings_RecentItemsCount_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pinned transformations first.
        /// </summary>
        internal static string Settings_SpecialItemsOrder_Choice_PinnedFirst {
            get {
                return ResourceManager.GetString("Settings_SpecialItemsOrder_Choice_PinnedFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent transformations first.
        /// </summary>
        internal static string Settings_SpecialItemsOrder_Choice_RecentFirst {
            get {
                return ResourceManager.GetString("Settings_SpecialItemsOrder_Choice_RecentFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items order.
        /// </summary>
        internal static string Settings_SpecialItemsOrder_Label {
            get {
                return ResourceManager.GetString("Settings_SpecialItemsOrder_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom behavior that may not fit other categories..
        /// </summary>
        internal static string TransformationCategory_Cleanup_Description {
            get {
                return ResourceManager.GetString("TransformationCategory_Cleanup_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleanup.
        /// </summary>
        internal static string TransformationCategory_Cleanup_Title {
            get {
                return ResourceManager.GetString("TransformationCategory_Cleanup_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handles separators but doesn&apos;t change case..
        /// </summary>
        internal static string TransformationCategory_Separators_Description {
            get {
                return ResourceManager.GetString("TransformationCategory_Separators_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separators.
        /// </summary>
        internal static string TransformationCategory_Separators_Title {
            get {
                return ResourceManager.GetString("TransformationCategory_Separators_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normalizes for code identifiers (removes diacritics, etc.)..
        /// </summary>
        internal static string TransformationCategory_Technical_Description {
            get {
                return ResourceManager.GetString("TransformationCategory_Technical_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical.
        /// </summary>
        internal static string TransformationCategory_Technical_Title {
            get {
                return ResourceManager.GetString("TransformationCategory_Technical_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preserves diacritics and linguistic features..
        /// </summary>
        internal static string TransformationCategory_Text_Description {
            get {
                return ResourceManager.GetString("TransformationCategory_Text_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string TransformationCategory_Text_Title {
            get {
                return ResourceManager.GetString("TransformationCategory_Text_Title", resourceCulture);
            }
        }
    }
}
